Source/MGI_Maritima/Controllers/Articulo/ArticuloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MGI_Maritima.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MGI_Maritima.Controllers.Articulo
{
    public class ArticuloController : Controller
    {
        private readonly InventarioContext _db;
        [BindProperty]
        public Models.Articulo articulo { get; set; }
        public ArticuloController(InventarioContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult UpInsert(int? id)
        {
            articulo = new Models.Articulo();
            if (id == null)
            {

                return View(articulo);
            }

            articulo = _db.articulos.FirstOrDefault(x => x.id == id);
            if (articulo == null)
            {
                return NotFound();
            }
            return View(articulo);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpInsert(IFormCollection data)
        {

            var json = data["DataPrecio"];
            List<DataPrecio> dataPrecios = JsonConvert.DeserializeObject<List<DataPrecio>>(json);
            if (ModelState.IsValid)
            {
                if (articulo.id == 0)
                {
                    _db.articulos.Add(articulo);
                }
                else
                {
                    _db.articulos.Update(articulo);
                }
                _db.SaveChanges();
                var _PreciosArticulos = _db.precios.Where(x => x.idArticulo == articulo.id).ToList();
                _db.precios.RemoveRange(_PreciosArticulos);
                _db.SaveChanges();
                if (dataPrecios != null)
                {
                    foreach (DataPrecio item in dataPrecios)
                    {

                        _db.precios.Add(new Precio() { id = 0, idArticulo = articulo.id, precio = item.precio });
                        _db.SaveChanges();

                    }
                }

                return RedirectToAction("Index");
            }
            return View(articulo);
        }



        #region Mis_Api
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {

            return Json(new { data = await _db.articulos.ToListAsync() });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var articuloFromDB = await _db.articulos.FirstOrDefaultAsync(x => x.id == id);
            if (articuloFromDB == null)
            {
                return Json(new { success = false, message = "Error Eliminando" });

            }
            var _PreciosArticulos = _db.precios.Where(x => x.idArticulo == articuloFromDB.id).ToList();
            _db.precios.RemoveRange(_PreciosArticulos);
            _db.SaveChanges();
            _db.articulos.Remove(articuloFromDB);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Eliminado" });

        }

        #endregion
    }
}

Source/MGI_Maritima/Controllers/Invenatario/InventarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using MGI_Maritima.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MGI_Maritima.Controllers.Invenatario
{
    public class InventarioController : Controller
    {
        private readonly InventarioContext _db; 
        public InventarioController(InventarioContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Reporte()
        {
            return View();
        }
        #region Mis_Api
        [HttpGet]
        public async Task<IActionResult> Get()
        {

            return Json(new { data = await _db.logInventarios.ToListAsync() });
        }
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
             
            return Json(new { data = await _db.inventarios.ToListAsync() });
        }
  
        [HttpPost]
        public async Task<IActionResult> PostInvenario(string data)
        {
            try
            {
                string _accion = "";
               
                var inventario = JsonConvert.DeserializeObject<InventarioData>(data);
                var finventario = await _db.inventarios.Where(x => x.idalmacen == inventario.idalmacen && x.idarticulo == inventario.idarticulo).FirstOrDefaultAsync();
                if (finventario != null)
                {
                    if (inventario.Accion == 1)
                    {
                        finventario.cantidad += inventario.cantidad;
                        _accion = "Entro";
                    }
                    else
                    {
                        finventario.cantidad -= inventario.cantidad;
                        _accion = "Salio";
                    }

                }
                else
                {
                    _accion = "Entro";
                    _db.inventarios.Add(new Inventario() {  idalmacen = inventario.idalmacen, idarticulo= inventario.idarticulo, cantidad = inventario.cantidad});
                }
                _db.logInventarios.Add(new LogInventario() { 
                    idarticulo = inventario.idarticulo, 
                    idubicacion = inventario.idalmacen, 
                    fecha = DateTime.Now, 
                    detalle = string.Format("El Articulo {0} {1} en el Almacen {2} la fecha {3}", GetNameArticulo(inventario.idarticulo), _accion, GetNameAlmacen(inventario.idalmacen), DateTime.Now.ToString()) });
               
                await _db.SaveChangesAsync();
                return Json(new { success = true, message = "Guardado" });
            }
            catch (Exception ex)
            {
                return Json(new { success = true, message = "No pudo guardar" });
            }
                
           
        }
        public   string GetNameArticulo(int? id)
        {
            Models.Articulo articulof =  _db.articulos.Find(id);
            return articulof.nombre;

        }
        public string GetNameAlmacen(int? id)
        {
            Models.Almacen  almacen =  _db.almacens.Find(id);
            return almacen.descripcion;

        }


        #endregion
    }
}

Source/MGI_Maritima/Controllers/Ubicacion/UbicacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MGI_Maritima.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MGI_Maritima.Controllers.Ubicacion
{
    public class UbicacionController : Controller
    {
        private readonly InventarioContext _db;
        [BindProperty]
        public Almacen   almacen { get; set; }
        public UbicacionController(InventarioContext db)
        {
            _db = db;

        }
        public IActionResult Index()
        { 
            return View();
        }
        public IActionResult UpInsert(int? id)
        {
            almacen = new Almacen();
            if (id == null)
            {
                return View(almacen);
            }
            almacen = _db.almacens.FirstOrDefault(x => x.id == id);
            if (almacen == null)
            {
                return NotFound();
            }
            return View(almacen);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpInsert()
        {
            if (ModelState.IsValid)
            {
                if (almacen.id == 0)
                {
                    _db.almacens.Add(almacen);
                }
                else
                {
                    _db.almacens.Update(almacen);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(almacen);
        }



        #region Mis_Api
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.almacens.ToListAsync() });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var almacenFromDB = await _db.almacens.FirstOrDefaultAsync(x => x.id == id);
            if (almacenFromDB == null)
            {
                return Json(new { success = false, message = "Error Eliminando" });

            }
            _db.almacens.Remove(almacenFromDB);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "Eliminado" }); 

        }

        #endregion
    }
}

Source/MGI_Maritima/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MGI_Maritima</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inventario Maritima</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articulo" asp-action="Index">Articulos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ubicacion" asp-action="Index">Almacen</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventario" asp-action="Index">Inventario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventario" asp-action="Reporte">Reporte</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MGI_Maritima - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

     <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>